### ISSUE TITLE
Autobuild on dockerhub?

### ISSUE THREAD

**Issue by kasbohm** [spiros/docker-ukbiobank-utils#2]
Hi, I could not find the repo on dockerhub. You could add docker autobuild by linking the github repo here:
https://hub.docker.com/repository/create

**Comment by spiros** [comment]
Hey, just to make sure, I already have this repo linked with dockerhub:

https://hub.docker.com/repository/docker/spiros123/ukbiobank-utils

or is this not what you mean?

**Comment by kasbohm** [comment]
Yep, just did not find it. Modified the PR #3  with the correct path.
