### ISSUE TITLE
How to run the docker-ukbiobank-utils

### ISSUE THREAD

**Issue by vittoriofortino84** [spiros/docker-ukbiobank-utils#4]
Hi,
I do not know how to exactly run this docker..
Perhaps, the following command is not working.. 

docker run -v $PWD --rm -it docker-ukbiobank-utils-master/ukbiobank-utils ukbunpack

"Unable to find image 'docker-ukbiobank-utils-master/ukbiobank-utils:latest' locally"..

Could you please help me with this issue?

Kind regards,

Vittorio

**Comment by davidparsson** [comment]
The name of the deployed image is `spiros123/ukbiobank-utils`. See https://hub.docker.com/r/spiros123/ukbiobank-utils for examples.
